# Model run parameters
data_dir: '../data_uploads'
results_dir: '../model_results'

# output scenario name
scenario_name: 'scenario_name'

##### -------------------------           input control           ------------------------- #####
# boolean parameters
re_cost_scenario: 'medium'       # or 'low' for low renewable generator and battery storage costs
fix_re_cap_boolean: False        # True: fix wind, solar, battery capacity
rgt_boolean: False               # True: the low_carbon input in "main.py" would be Renewable
nuclear_boolean: False           # True: allow nuclear; False: no nuclear
h2_boolean: False                # True: allow H2 storage; False: H2 storage
new_gt_boolean: True             # True: allow GT capacity above "gt_current_mix_cap_mw" listed below
same_eheating_ev_rate_boolean: True   # True: same electrification rates for heating and vehicles; False, diff. rates
same_nodal_elecfx_rates_boolean: True  # True: each node has same electrification rate; Only use false with config = 1
btmpv_count_re : False               # True: btmpv generation can be count as renewable generation
elecfx_constraint_ge: False      # True: set the smallest electrification ratio numbers, False: set the fixed numbers
gt_based_on_current: True        # True: >= fixed 1999 MW new GT; False: >= 0 MW new GT (True for retiring IP...
short-term study; False: for full page or high RE penetration ~100%)
ev_set_profile_boolean: True     # True: Used user-provided EV charging profile; False: uses inputs under "EV" below

# input year
proj_year: 2030    # input > 2019, use the projection BTM PV; input = 2019, use the btmpv_existing_mw

# General model assumptions
num_years: 1
num_hours: 8760
num_nodes: 4
i_rate: 0.05

## Utility-scale solar (solar) and behind-the-meter (btmpv) solar assumptions:
# Costs
solar_capex_medium_mw: [1.341e6, 1.341e6, 1.593e6, 1.593e6]
solar_capex_low_mw: [1.006e6, 1.006e6, 1.195e6, 1.195e6]
solar_om_cost_mw_yr: 10.4e3
# Capacities
solar_cap_existing_mw: [0,  0,  0,  56.5]
solar_cap_limit_mw: [212710, 44899, 481, 2743]
btmpv_cap_existing_mw: [562, 523, 293, 259]
btmpv_dist: [0.3192, 0.3577, 0.1659, 0.1572]

## Wind assumptions
# Cost
onshore_capex_medium_mw: 1.992e6
onshore_capex_low_mw: 1.698e6
onshore_om_cost_mw_yr: 18.1e3
offshore_capex_medium_mw: 3.583e6
offshore_capex_low_mw: 2.256e6
offshore_om_cost_mw_yr: 3.8e4
# Capacities
onshore_cap_existing_mw: [1985.25, 0, 0, 0]
onshore_cap_limit_mw: [32402, 4376, 0, 0]
offshore_cap_existing_mw: [0, 0, 0, 0]
offshore_cap_total_limit_mw: 57938

## Battery storage assumptions
# Cost
battery_capex_medium_mw: 0
battery_capex_low_mw: 0
battery_capex_medium_mwh: 208e3
battery_capex_low_mwh: 144e3
# Efficiencies, self-discharge, p2e ratio constraint, existing capacties
battery_eff: 0.946 # One way - same efficiency on charge and discharge
battery_self_discharge: 0.001
battery_p2e_ratio_range: [0.25, 0.25] # Input min and max; if same, model will adjust constraint accordingly
existing_battery_cap_mw:  [3, 20, 0, 10]
existing_battery_cap_mwh: [5.2, 80, 0, 65]

## H2 storage assumptions
# Cost
h2_capex_mw: [3.013e6, 3.013e6, 4.036e6, 4.036e6]
h2_capex_mwh: [360, 8.29e3, 8.29e3, 8.29e3]
h2_om_cost_mw_yr: 48.87e3
# Efficiencies, self-discharge, p2e ratio constraint,
h2_eff: 0.592
h2_self_discharge: 0.001
h2_p2e_ratio_range: [0, 1e100] # Input min and max; if same, model will adjust constraint accordingly


## Gas turbine assumption
# Shared (assumption applt to new and existing GT)
gt_capex_mw: [0.772e6, 0.772e6, 1.034e6, 1.034e6]
gt_fuel_cost_mwh: [9.86, 13.79, 12.54, 12.35]
# New GT assumptions (costs and efficiencies)
new_gt_startup_cost_mw: 69
new_gt_om_cost_mwh: 4.48
new_gt_om_cost_mw_yr: 6.97e3
new_gt_efficiency: 0.344
# Existing GT assumptions (costs, existing capacity, efficiency, and addl. cap from simulations)
existing_gt_startup_cost_mw: 79
existing_gt_cap_mw: [3934.2, 8622.5, 10249.9, 4192.7]
existing_gt_efficiency: 0.428
current_scenario_addl_gt_cap: [0, 1132, 0, 867] # based on the 'current' scenario in the model

## nodal nuclear, hydro, and biofuel RE generation assumptions
# Nuclear
nuc_cost_mwh: [37.94, 0, 26.82, 0]
nuc_cap_mw: [3536.8, 0, 0, 0] # current w/ IP: [3536.8, 0, 2311, 0]; 2030: [3536.8, 0, 0, 0]
nuc_avg_gen_mw: [3207, 0, 0, 0] # current w/ IP: [3207, 0, 1906, 0]; 2030: [3207, 0, 0, 0]

# Hydropower
hydro_cost_mwh: [18.47, 28.02, 0, 0]
hydro_avg_gen_mw: [2728, 269, 0, 0]  # average generation
hydro_cap_mw: [4717.4, 608.7, 0, 0]
flex_hydro_cap_mw: [769.4, 608.7, 0, 0]

# Biofuel
biofuel_cap_mw: [258.0, 45.0, 59.7, 142.2]
biofuel_daily_gen_mwh: [3289.041, 473.425, 1046.575, 2445.479]
biofuel_cost_mwh: [20.66, 27.41, 27.05, 32.29]

## Imported electricity assumptions
import_limit_mw: [1500, 0, 1250, 0]  # 2030: [1500, 0, 1000, 0]; current: [1500, 0, 0, 0]
import_cost_mwh: [22.13, 0, 70, 0]
hqch_capacity_factor: 0.9

## Existing capacity and transmission cost assumptions
cap_market_cost_mw_yr: [27640, 53440, 101303, 104600]  # $/MW-yr
existing_trans_load_mwh_yr: [69.683e6, 75.52e6] # MWh sales in {nodes 1 & 2}, {nodes 3 and 4}
existing_trans_cost_mwh: [16.9, 27.3] # $/MWh transmision average price component for {nodes 1 & 2}, {nodes 3 and 4}

## EV assumptions
ev_full_cap_mw: 6716
ev_charging_p2e_ratio: 0.166666667
ev_hours_start: 0 # 0 UTC is the 19:00 PM in NY
ev_charging_hours: 24
ev_charging_method: 'flexible' # or 'fixed'
ev_load_dist: [0.3609526, 0.1747773, 0.2518691, 0.2124010]

# Other assumptions
trans_loss: 0.03
reserve_req: 1.189
nominal_storage_cost: 0.01
nominal_trans_cost_mwh: 0.01

## Emissions assumptions -- all quantities measured in CO2e
baseline_emissions_mmt: 302.770
ng_e_factor_t_mwh: 0.3966601
flex_heating_emissions_mmt: [36.518, 14.457, 37.044, 13.641]
flex_trans_emissions_mmt: 73.703
fixed_trans_emissions_mmt: 21.956
fixed_ind_emissions_mmt: 19.365
waste_emissions_mmt: 2.784

# Gurobi solver parameters
feasibility_tol: 0.01
optimality_tol: 0.01
method: 2
bar_conv_tol: 0
bar_order: 0
crossover: 0
nonconvex: 2
