# Model run parameters
data_dir: '../data_uploads'
results_dir: '../model_results'

# output scenario name
scenario_name: 'scenario_name'

##### -------------------------           input control           ------------------------- #####
# boolean parameters
re_cost_scenario: 'medium'          # or 'low' for low renewable generator and battery storage costs
fix_re_cap_boolean: False        # True: fix wind, solar, battery capacity
rgt_boolean: False               # True: the low_carbon input in "main.py" would be Renewable
nuclear_boolean: False           # True: allow nuclear; False: no nuclear
h2_boolean: False                # True: allow H2 storage; False: H2 storage
new_gt_boolean: True             # True: allow GT capacity above "gt_current_mix_cap_mw" listed below
same_eheating_ev_rate_boolean: True   # True: same electrification rates for heating and vehicles; False, diff. rates
same_nodal_elecfx_rates_boolean: True  # True: each node has same electrification rate; Only use false with config = 1
btmpv_count_re: False               # True: btmpv generation can be count as renewable generation
elecfx_constraint_ge: False      # True: set the smallest electrification ratio numbers, False: set the fixed numbers
dss_synthetic_ts: False          # True: use 50% DSS synthetic TS, False: full heating electrification
gt_based_on_current: False        # True: >= fixed 1999 MW new GT; False: >= 0 MW new GT (True for retiring IP...
ev_set_profile_boolean: True     # True: Used user-provided EV charging profile; False: uses inputs under "EV" below
greenfield_boolean: True        # True: Set existing GT, solar, wind, tx, hydro to zero
copper_plate_boolean: False      # True: Set copper plate transmission condition
same_nodal_costs: True          # True: Set nodal costs to be the same

# input year
proj_year: 2030    # input > 2019, use the projection BTM PV; input = 2019, use the btmpv_existing_mw

# General model assumptions
num_years: 6
num_hours: 52608
num_nodes: 4
i_rate: 0.05

## Utility-scale solar (solar) and behind-the-meter (btmpv) solar assumptions:
# Costs
solar_capex_medium_mw: [1.341e6, 1.341e6, 1.593e6, 1.593e6]
solar_capex_low_mw: [1.006e6, 1.006e6, 1.195e6, 1.195e6]
solar_om_cost_mw_yr: 10.4e3
# Capacities
solar_cap_existing_mw: [0,  0,  0,  0] # changed for greenfield
solar_cap_limit_mw: [212710, 44899, 481, 2743]
btmpv_cap_existing_mw: [0, 0, 0, 0] # changed for greenfield
btmpv_dist: [0.3192, 0.3577, 0.1659, 0.1572]

## Wind assumptions
# Cost
onshore_capex_medium_mw: 1.992e6
onshore_capex_low_mw: 1.698e6
onshore_om_cost_mw_yr: 18.1e3
offshore_capex_medium_mw: 3.583e6
offshore_capex_low_mw: 2.256e6
offshore_om_cost_mw_yr: 3.8e4
# Capacities
onshore_cap_existing_mw: [0, 0, 0, 0] # changed for greenfield
onshore_cap_limit_mw: [32402, 4376, 0, 0]
offshore_cap_existing_mw: [0, 0, 0, 0]
offshore_cap_total_limit_mw: 57938

## Battery storage assumptions
# Cost
battery_capex_medium_mw: 0
battery_capex_low_mw: 0
battery_capex_medium_mwh: 208e3
battery_capex_low_mwh: 144e3
# Efficiencies, self-discharge, p2e ratio constraint, existing capacties
battery_eff: 0.946 # One way - same efficiency on charge and discharge
battery_self_discharge: 0.001
battery_p2e_ratio_range: [0.25, 0.25] # Input min and max; if same, model will adjust constraint accordingly
existing_battery_cap_mw:  [0, 0, 0, 0]  # changed for greenfield
existing_battery_cap_mwh: [0, 0, 0, 0]  # changed for greenfield

## H2 storage assumptions
# Cost
h2_capex_mw: [3.013e6, 3.013e6, 4.036e6, 4.036e6]
h2_capex_mwh: [350, 8.29e3, 8.29e3, 8.29e3]
h2_om_cost_mw_yr: 48.87e3
# Efficiencies, self-discharge, p2e ratio constraint,
h2_eff: 0.592
h2_self_discharge: 0.001
h2_p2e_ratio_range: [0, 1e100] # Input min and max; if same, model will adjust constraint accordingly


## Gas turbine assumption
# Shared (assumption applies to new and existing GT)
gt_capex_mw: [0.772e6, 0.772e6, 1.034e6, 1.034e6]
gt_fuel_cost_mwh: [9.86, 13.79, 12.54, 12.35]

# New GT assumptions (costs and efficiencies)
new_gt_startup_cost_mw: 69
new_gt_om_cost_mwh: 4.48
new_gt_om_cost_mw_yr: 6.97e3
new_gt_efficiency: 0.344
# Existing GT assumptions (costs, existing capacity, efficiency, and addl. cap from simulations)
existing_gt_startup_cost_mw: 79
existing_gt_cap_mw: [0, 0, 0, 0] # changed for greenfield
existing_gt_efficiency: 0.428
current_scenario_addl_gt_cap: [0, 1132, 0, 867] # based on the 'current' scenario in the model

## nodal nuclear, hydro, and biofuel RE generation assumptions
# Nuclear
nuc_cost_mwh: [37.94, 0, 26.82, 0]
nuc_cap_mw: [0, 0, 0, 0] # current w/ IP: [3536.8, 0, 2311, 0]; 2030: [3536.8, 0, 0, 0], # changed for greenfield
nuc_avg_gen_mw: [0, 0, 0, 0] # current w/ IP: [3207, 0, 1906, 0]; 2030: [3207, 0, 0, 0]  # changed for greenfield

# Hydropower
hydro_cost_mwh: [18.47, 28.02, 0, 0]
#hydro_avg_gen_mw: [2723, 270, 0, 0]  # average generation
hydro_cap_mw: [0, 0, 0, 0]  # changed for greenfield
flex_hydro_cap_mw: [0, 0, 0, 0]  # changed for greenfield

# Biofuel
biofuel_cap_mw: [0, 0, 0, 0] # changed for greenfield
biofuel_daily_gen_mwh: [0, 0, 0, 0] # changed for greenfield
biofuel_cost_mwh: [20.66, 27.41, 27.05, 32.29]

## Constant costs for nodal equivalency
solar_capex_medium_constant_mw: [1362820, 1362820, 1362820, 1362820]
gt_capex_constant_mw: [862190, 862190, 862190, 862190]
gt_fuel_cost_constant_mwh: [11.32, 11.32, 11.32, 11.32]


## Imported electricity assumptions
import_limit_mw: [0, 0, 0, 0] # changed for greenfield
import_cost_mwh: [22.13, 0, 70, 0]
hqch_capacity_factor: 0.9

## Existing capacity and transmission cost assumptions
cap_market_cost_mw_yr: [27640, 53440, 101303, 104600]  # $/MW-yr
existing_trans_load_mwh_yr: [0, 0] # changed for greenfield
existing_trans_cost_mwh: [16.9, 27.3] # $/MWh transmision average price component for {nodes 1 & 2}, {nodes 3 and 4}

## EV assumptions
ev_full_cap_mw: 6716
ev_charging_p2e_ratio: 0.166666667
ev_hours_start: 0 # 0 UTC is the 19:00 PM in NY
ev_charging_hours: 24
ev_charging_method: 'flexible' # or 'fixed'
icv_load_dist: [0.3609526, 0.1747773, 0.2518691, 0.2124010]  # traditional internal combustion vehicle distribution

# Other assumptions
trans_loss: 0.03
reserve_req: 1.189
nominal_storage_cost: 0.01
nominal_trans_cost_mwh: 0.01

## Emissions assumptions -- all quantities measured in CO2e
baseline_emissions_mmt: 302.770
ng_e_factor_t_mwh: 0.3966601
flex_space_heating_emissions_mmt: [26.305, 12.388, 27.026, 11.749]
flex_const_heating_emissions_mmt: [9.477, 4.732, 13.517, 5.660]
flex_trans_emissions_mmt: 73.703
fixed_trans_emissions_mmt: 21.956
fixed_ind_emissions_mmt: 19.365
waste_emissions_mmt: 2.784

# Gurobi solver parameters
feasibility_tol: 0.01
optimality_tol: 0.01
method: 2
bar_conv_tol: 0
bar_order: 0
crossover: 0
nonconvex: 2
